# Site settings
title: Scott Dixon
email: dixon.scottr@gmail.com
url: http://dixonscottr.github.io/
description: "Full-stack web developer | former journalist"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: 

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/dixonscottr
  - title: github
    url: https://github.com/dixonscottr
  - title: twitter
    url: https://twitter.com/realscottdixon

# Build settings
markdown: kramdown
permalink: pretty
